### ISSUE TITLE
Alle Parameter verfügbar machen

### ISSUE THREAD

**Issue by Misco** [fritzmg/contao-youtube-iframe#3]
https://developers.google.com/youtube/player_parameters?hl=de#Parameters

dann ist es Perfekt.

**Comment by fritzmg** [comment]
Tatsächlich kannst du weitere Parameter selbst hinzufügen. Wenn du bspw. `disablekb=1` zur Auswahl haben möchtest, müsstest du folgendes machen:

Einen Parameternamen zu `$GLOBALS['YT_PARAMS']` hinzufügen:
```php
$GLOBALS['YT_PARAMS'][] = 'disablekb`;
```
Den URL Parameter in `$GLOBALS['YT_PARAMS_MAPPING']` hinzufügen, der benutzt wird, wenn der Parameter im Backend ausgewählt wurde:
```php
$GLOBALS['YT_PARAMS_MAPPING'][] = 'disablekb=1';
```
Eine Übersetzung für das Backend hinzufügen:
```php
$GLOBALS['TL_LANG']['tl_content']['ytParamsReference']['disablekb'] = 'Tastatursteuerung deaktivieren';
```

**Comment by fritzmg** [comment]
I have decided to not put any more detailed work into this extension, since the given functionality is now implemented in Contao `4.5`.

Unfortunately, in Contao `4.5` it is not possible to extend the available parameters like in this extension. However, you could make a feature request for that or for certain parameters in the [core-bundle](https://github.com/contao/core-bundle/issues).
